analyzer_rules:
    - unused_import
    - unused_private_declaration
disabled_rules:
    - nesting
opt_in_rules:
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - contains_over_first_not_nil
    - empty_string
    - extension_access_modifier
    - fatal_error_message
    - file_header
    - file_name
    - first_where
    - identical_operands
    - joined_default_parameter
    - let_var_whitespace
    - last_where
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - redundant_nil_coalescing
    - redundant_type_annotation
    - sorted_first_last
    - static_operator
    - unneeded_parentheses_in_closure_argument
    - untyped_error_in_catch
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition
    - empty_count
# Must check of we are going to add this rules too
#- number_separator
#- object_literal
#- private_action
#- private_outlet

excluded:
- Pod

line_length:
    warning: 160
    error: 200

file_length:
    warning: 500
    error: 600

type_name:
    warning: 40
    error: 50

type_body_length:
    warning: 300
    error: 400

function_body_length:
    warning: 40
    error: 50
