name: Build and test using Tuist

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout
        run: bash <(curl -Ls https://install.tuist.io)
      - name: Create Xcode project
        run: tuist generate --project-only
      - name: Build
        run: tuist build
      - name: Run tests
        run: tuist test
