name: Build and test using Tuist

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Tests
        uses: tuist/tuist-action@0.1.8
        with:
          command: "test"
          arguments: "Mimic"
