name: Test
on: [pull_request]

jobs:
  iOS:
    name: Test on iOS
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 11', 'platform=iOS Simulator,name=iPhone 8']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: 
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project Mimic.xcodeproj -scheme Mimic -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO clean test | xcpretty
        env: 
         destination: ${{ matrix.destination }}
